name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: AVKNHTEMS649012

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Login no Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Tag da Imagem Docker
        run: |
           docker build -t calculadora-node .
           docker tag calculadora-node:latest docker.io/lfcamargo/calculadora-node:latest
      
      - name: Push da Imagem Docker
        run: docker push docker.io/lfcamargo/calculadora-node:latest

      - name: SonarQube Scan
        run: docker run -e SONAR_HOST_URL=http://host.docker.internal:9000 -e SONAR_LOGIN=sqp_6cef8b1e52fd57e67f855b1255c1f0a3b715151d -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli

      - name: Parar e Remover o Container Anterior
        run:  | 
           if (docker ps -a | Where-Object { $_ -match 'calculadora-node' }) {
             docker stop calculadora-node
             docker rm calculadora-node
           } else {
             Write-Host "Aplicação Calculadora não está ativa."
           }
      
      - name: Iniciar um Novo Container
        run: docker run -d -p 3000:3000 --name calculadora-node calculadora-node:latest
    
