name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: AVKNHTEMS649012

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Login no Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Tag da Imagem Docker
        run: |
           docker build -t calculadora-node .
           docker tag calculadora-node:latest docker.io/lfcamargo/calculadora-node:latest
      
      - name: Push da Imagem Docker
        run: docker push docker.io/lfcamargo/calculadora-node:latest

      - name: SonarQube Scan
        run: docker run -e SONAR_HOST_URL=http://host.docker.internal:9000 -e SONAR_LOGIN=sqp_6cef8b1e52fd57e67f855b1255c1f0a3b715151d -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli
      
      - name: TrivyScan - IMAGE 
        run: docker run --rm -v $PWD/:/myapp aquasec/trivy image --format template --template "@/myapp/html.tpl" -o /myapp/relatorios_trivy/scan_image.html --severity HIGH,CRITICAL lfcamargo/calculadora-node:latest

      - name: TrivyScan - CONFIGs Projeto
        run: docker run --rm -v $PWD/:/myapp aquasec/trivy config --format template --template "@/myapp/html.tpl" -o /myapp/relatorios_trivy/scan_config.html /myapp

      #- name: TrivyScan - Repositorio
      #  run: docker run --rm -v $PWD/:/myapp aquasec/trivy repo --format template --template "@/myapp/html.tpl" -o /myapp/relatorios_trivy/scan_repo.html https://github.com/lfcamargo1991/calculator.git

      - name: TrivyScan - FileSystem
        run: docker run --rm -v $PWD/:/myapp aquasec/trivy fs --format template --template "@/myapp/html.tpl" -o /myapp/relatorios_trivy/scan_fs.html /myapp
        
      - name: Parar e Remover o Container Anterior
        run:  | 
           if (docker ps -a | Where-Object { $_ -match 'calculadora-node' }) {
             docker stop calculadora-node
             docker rm calculadora-node
           } else {
             Write-Host "Aplicação Calculadora não está ativa."
           }

      - name: Iniciar um Novo Container
        run: docker run -d -p 3000:3000 --name calculadora-node calculadora-node:latest
    
