name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  #deploy:
  build:
    runs-on: AVKNHTEMS649012

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      #- name: Login no Docker
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Tag da Imagem Docker
        run: |
          whoami
          docker build -t calculadora-node .
        #  docker tag calculadora-node:latest docker.io/lfcamargo/calculadora-node:latest

      #- name: Push da Imagem Docker
      #  run: docker push docker.io/lfcamargo/calculadora-node:latest

      - name: Parar e Remover o Container Anterior
        run: docker stop calculadora-node ; docker rm calculadora-node

      - name: Iniciar um Novo Container
      #  run: docker run -d -p 3000:3000 --name calculadora-node docker.io/lfcamargo/calculadora-node:latest
        run: docker run -d -p 3000:3000 --name calculadora-node calculadora-node:latest
    
