name: Publish Docker image

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Login no Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io/lfcamargo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Tag da Imagem Docker
        run: |
          docker build -t calculadora-node .
          docker tag calculadora-node:latest docker.io/lfcamargo/calculadora-node:latest

      - name: Push da Imagem Docker
        run: docker push docker.io/lfcamargo/calculadora-noder:latest

      - name: Parar e Remover o Container Anterior
        run: docker stop calculadora-node || true && docker rm calculadora-node || true

      - name: Iniciar um Novo Container
        run: docker run -d -p 80:80 --name calculadora-node docker.io/lfcamargo/calculadora-node:latest
    
